version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine3.18
    volumes:
      - trello_postgres_data:/var/lib/postgresql/dta/
    environment:
      - POSTGRES_USER=trello
      - POSTGRES_PASSWORD=1234trello
      - POSTGRES_DB=trello_dev

volumes:
  trello_postgres_data:

