version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn trello.wsgi:application --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine3.18
    restart: always
    volumes:
      - trello_postgres_data:/var/lib/postgresql/dta/
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  trello_postgres_data:
