# Generated by Django 4.2.3 on 2023-08-05 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='work_space',
            field=models.ForeignKey(help_text='work space of the board', on_delete=django.db.models.deletion.CASCADE, related_name='work_space_boards', to='dashboards.workspace', verbose_name='Workspace'),
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(help_text='Title of the Tasklist', max_length=150, verbose_name='Title')),
                ('board', models.ForeignKey(help_text='Board associated with the Tasklist', on_delete=django.db.models.deletion.CASCADE, related_name='board_Tasklists', to='dashboards.board', verbose_name='Board')),
            ],
            options={
                'verbose_name': 'TaskList',
                'verbose_name_plural': 'TaskLists',
                'ordering': ['board'],
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(help_text='Status of the task', on_delete=django.db.models.deletion.CASCADE, related_name='status_tasks', to='dashboards.tasklist', verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
