# Generated by Django 4.2.3 on 2023-08-05 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboards', '0002_alter_board_work_space_tasklist_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='doer',
            field=models.ForeignKey(help_text='Doer of the activity', on_delete=django.db.models.deletion.DO_NOTHING, related_name='doer_activity', to=settings.AUTH_USER_MODEL, verbose_name='Doer'),
        ),
    ]
