# Generated by Django 4.2.3 on 2023-08-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_activity_doer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=1, help_text='Order of the task', verbose_name='Order'),
        ),
    ]
