# Generated by Django 4.2.3 on 2023-08-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('title', 'board')},
        ),
    ]
