# Generated by Django 4.2.3 on 2023-08-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that email already exists.'}, max_length=11, null=True, unique=True, verbose_name='mobile number'),
        ),
    ]
