# Generated by Django 4.2.3 on 2023-08-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecycle',
            fields=[
            ],
            options={
                'verbose_name': 'UserRecycle',
                'verbose_name_plural': 'UsersRecycle',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that mobile already exists.'}, max_length=11, null=True, unique=True, verbose_name='mobile number'),
        ),
    ]
